### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by yemheno** [techops-recsys-lateral-hiring/developer-joyofenergy-java#21]
Dear Devs,
I'm in a dire need of a preparation session. I'm supposed to present at 14:30 ATM but after installing and studying during the weekend, I'm still completely lost. Java wasn't even my language of choice and I'm ashamed to admit I can hardly follow the components.
The best,
Pablo.

**Comment by albertattard** [comment]
Hello Pablo.

Thank you for your email.

Are you a Thoughtworker or a candidate?  If you are a Thoughtworker, can
you please reach out to me on Google chat (*Albert Attard*)?

With kind regards,
Albert Attard

**Comment by yemheno** [comment]
Dear Albert,
I'm a candidate for the trainee program. I'm shifting from theoretical
physics and consequently, I'm quite lacking in Dev specifics. However, I
just love programming. I regret the day I turned down a Research position
in computational physics. I really want to learn and understand the code so
I need a guide to start dismembering the components.
The best,
Pablo.
Ph. D. in Physics.

**Comment by albertattard** [comment]
Good morning Pablo,

I would recommend you to brush up on your programming skills before
attending the interview.  This may require some time though.  There are
many good books or tutorials that you can follow.  Java is a well
established language and there is ample documentation available.

I hope this helps.  If you have any specific questions, please don't
hesitate to reach out.

Wish you best of luck.

With kind regards,
Albert Attard

**Comment by jejking-tw** [comment]
Closing as part of ongoing housekeeping on the git repositories.
