### ISSUE TITLE
Upgrade to Java 11+

### ISSUE THREAD

**Issue by tw-xren** [techops-recsys-lateral-hiring/developer-joyofenergy-java#22]
Hi folks,

Given [java 8 's Premier support has expired](https://www.oracle.com/java/technologies/java-se-support-roadmap.html), shall we migrate this repo to Java 11 or 17 ?

**Comment by eddientim** [comment]
Sounds like a great idea

**Comment by jejking-tw** [comment]
In the meantime we have moved this project to JDK 17.
